#!/bin/bash
# Moves selected window to bottom RIGHT of display.

current=$(xdotool getwindowfocus)

# Window will take up no more than 1/3 of width or height of screen.
new_width=$(($(xdotool getdisplaygeometry | awk '{print $2}') / 3))
new_height=$(($(xdotool getdisplaygeometry | awk '{print $1}') / 3))

xdotool windowsize $current $new_height $new_width

# Moves new window
new_h_size=$(xdotool getwindowgeometry $current | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')
new_w_size=$(xdotool getwindowgeometry $current | grep Geometry | sed -e 's/x/ /g' | awk '{print $2}')

height=$(($(xdotool getdisplaygeometry | awk '{print $2}') - new_h_size))
width=$(($(xdotool getdisplaygeometry | awk '{print $1}') - new_w_size))

xdotool windowmove $current $width $height
